### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getItem' of undefined

### ISSUE THREAD

**Issue by dingjie** [dingjie/atom-sync#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-sync](https://github.com/dingjie/atom-sync) package, v0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getItem' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:759

TypeError: Cannot read property 'getItem' of undefined
  at Object.module.exports.ConfigHelper.getCurrentProjectDirectory (/Users/dingjie/github/atom-sync/lib/helper/config-helper.coffee:57:53)
  at Object.module.exports.ConfigHelper.getFullPath (/Users/dingjie/github/atom-sync/lib/helper/config-helper.coffee:46:17)
  at Object.module.exports.ConfigHelper.load (/Users/dingjie/github/atom-sync/lib/helper/config-helper.coffee:13:17)
  at Object.module.exports.ServiceController.uploadEditingFile (/Users/dingjie/github/atom-sync/lib/controller/service-controller.coffee:25:26)
  at /Users/dingjie/github/atom-sync/lib/atom-sync.coffee:31:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1016:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:998:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:317:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:05.7.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:01.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.0
atom-sync, v0.4.1
atom-ternjs, v0.6.4
autocomplete-php, v0.3.6
chester-atom-syntax, v0.1.1
color-picker, v2.0.4
emmet, v2.3.10
file-icons, v1.5.7
fonts, v0.4.2
linter, v0.12.7
linter-csslint, v0.0.13
linter-htmlhint, v0.0.16
linter-jshint, v0.1.6
linter-less, v0.5.0
linter-php, v0.0.15
minimap, v4.9.4
minimap-find-and-replace, v4.2.0
travis-ci-status, v0.15.0

# Dev
No dev packages
```

**Comment by dingjie** [comment]
When the tree view is hide, getCurrentProjectDirectory cannot get real path by tree structure, looking for alternative way to get current root node

**Comment by Bulletninja** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [atom-sync](https://github.com/dingjie/atom-sync) package, v0.5.2


### Stack Trace

Uncaught TypeError: Cannot read property 'getItem' of undefined

```
At /Users/luis/.atom/packages/atom-sync/lib/atom-sync.coffee:15

TypeError: Cannot read property 'getItem' of undefined
  at atom-workspace.subscriptions.add.atom.commands.add.atom-sync:download-directory (/Users/luis/.atom/packages/atom-sync/lib/atom-sync.coffee:15:65)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:157:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -0:26.6.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:23.4.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:12.7.0 application:add-project-folder (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
atom-sync, v0.5.2

# Dev
No dev packages
```
