### ISSUE TITLE
atom-sync get error that tree-view panel closed

### ISSUE THREAD

**Issue by zlstone** [dingjie/atom-sync#20]
[Enter steps to reproduce below:]

1. use command+\ to close tree-view panel
2. save to upload file

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-sync](https://github.com/dingjie/atom-sync) package, v0.5.2

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:829

TypeError: Cannot read property 'indexOf' of undefined
    at Object.module.exports.ConfigHelper.isExcluded (/Users/leozhao/.atom/packages/atom-sync/lib/helper/config-helper.coffee:33:20)
    at Object.module.exports.ServiceController.onSync (/Users/leozhao/.atom/packages/atom-sync/lib/controller/service-controller.coffee:44:20)
    at Object.module.exports.ServiceController.onSave (/Users/leozhao/.atom/packages/atom-sync/lib/controller/service-controller.coffee:27:10)
    at /Users/leozhao/.atom/packages/atom-sync/lib/atom-sync.coffee:31:29
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1060:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1030:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:588:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:633:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -8:50.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -8:50.1.0 editor:newline (atom-text-editor.editor.is-focused)
  8x -8:48.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:05.6.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:33.6.0 tree-view:toggle (button.btn.btn-default.icon.icon-link)
     -0:06.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:03.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "activate-power-mode",
      "project-sidebar"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-jade, v0.3.0
atom-material-syntax, v0.2.10
atom-material-ui, v0.8.0
atom-sync, v0.5.2
emmet, v2.3.17
file-icons, v1.6.13
git-log, v0.4.1
highlight-selected, v0.11.1
language-babel, v2.6.2
minimap, v4.18.1
pigments, v0.19.3
project-manager, v2.6.5
rest-client, v0.5.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by dingjie** [comment]
更新到最新的 0.6.0 版本应该不会再有这个情况

**Comment by zlstone** [comment]
嗯，已更新。谢谢
