### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by cento** [dingjie/atom-sync#24]
[Enter steps to reproduce below:]

1. modify a file
2. try to upload folder using Command Palette instead of context menu

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-sync](https://github.com/dingjie/atom-sync) package, v0.6.0

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.normalize (path.js:448:3)
    at Object.module.exports.ServiceController.onSync (/Users/cento/.atom/packages/atom-sync/lib/controller/service-controller.coffee:34:20)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-sync:upload-directory (/Users/cento/.atom/packages/atom-sync/lib/atom-sync.coffee:22:25)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:31 editor:indent-selected-rows (atom-text-editor.editor.is-focused)
     -1:26.5.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -1:26.1.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:23.9.0 editor:indent-selected-rows (atom-text-editor.editor.is-focused)
     -1:20.4.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -1:19.4.0 core:select-up (atom-text-editor.editor.is-focused)
     -1:18.2.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:17.5.0 editor:indent-selected-rows (atom-text-editor.editor.is-focused)
     -1:13.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:57 editor:newline (atom-text-editor.editor.is-focused)
     -0:54.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:25.5.0 terminal-plus:toggle (atom-text-editor.editor.is-focused)
     -0:04.9.0 command-palette:toggle (textarea.)
     -0:03.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 atom-sync:upload-directory (textarea.)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.cpp": [
        "h"
      ]
    },
    "disabledPackages": [
      "compare-files",
      "autocomplete-css",
      "autocomplete-html",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-html",
      "language-java",
      "language-javascript",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-sql",
      "language-toml",
      "language-xml",
      "language-yaml",
      "metrics",
      "remote-sync"
    ],
    "projectHome": "/Users/cento/Desktop/Devel",
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-sync, v0.6.0
autocomplete-clang, v0.8.9
build, v0.54.1
clipboard-history, v0.6.6
file-icons, v1.6.14
file-watcher, v0.4.0
highlight-line, v0.11.1
minimap, v4.19.0
minimap-autohide, v0.10.1
open-recent, v5.0.0
remote-atom, v1.3.9
symbols-tree-view, v0.11.0
sync-settings, v0.6.0
term3, v0.21.0
terminal-plus, v0.14.5
time-status, v1.1.2

# Dev
No dev packages
```

**Comment by lpasqualis** [comment]
Have the same issue. Any workaround or solution?

**Comment by dpavlic** [comment]
The issue appears to stem from https://github.com/dingjie/atom-sync/blob/master/lib/atom-sync.coffee, specficially how paths get resolved in line 40/41.

    getSelectedPath: (target) ->
            (if ($ target).is 'span' then $ target else ($ target).find 'span')?.attr 'data-path'

If span is not found -- which it will not be when we are not using tree view -- it returns nothing.  It looks to me like this needs to be changed to alternatively look for a file in the current buffer if we choose to upload a file from the command palette.  I'm not sure about the behaviour of the upload directory in the command palette: would it be just the directory where the file is sitting?  If so, looks to me like there needs to be another command palette option to sync up to the root folder.

In any case, if our gracious host doesn't get to this soon, I can see if I can get a pull request going, but I am quite busy (crunch work time) and have little experience with CoffeeScript, although it looks to me like a solution should be relatively simple to cobble.

**Comment by dpavlic** [comment]
For now I've forked the repo fixing the problem; as I know 0 CoffeeScript, and Javascript is mostly on an off-and-on basis, this is surely inefficient, but it fixes the problem.  As a result, holding off on a pull request right this moment, but it does appear to fix the problem as best as short time could.  Diff is here:

https://github.com/dingjie/atom-sync/compare/master...dpavlic:master

**Comment by dingjie** [comment]
[Merged](https://github.com/dingjie/atom-sync/commit/7848d792d5c4911bbd6077c541e4c9c26c314e65) patch from dpavlic, thx!
