### ISSUE TITLE
Failed to load the atom-sync package

### ISSUE THREAD

**Issue by joannadal** [dingjie/atom-sync#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Ubuntu 14.04.2
**Thrown From**: [atom-sync](https://github.com/dingjie/atom-sync) package, v0.4.4

### Stack Trace

Failed to load the atom-sync package

```
At Cannot find module 'CSON'

Error: Cannot find module 'CSON'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/joan/.atom/packages/atom-sync/lib/helper/config-helper.coffee:2:8)
  at Object.<anonymous> (/home/joan/.atom/packages/atom-sync/lib/helper/config-helper.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/joan/.atom/packages/atom-sync/lib/controller/service-controller.coffee:6:16)
  at Object.<anonymous> (/home/joan/.atom/packages/atom-sync/lib/controller/service-controller.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/joan/.atom/packages/atom-sync/lib/atom-sync.coffee:3:14)
  at Object.<anonymous> (/home/joan/.atom/packages/atom-sync/lib/atom-sync.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:709:34)
  at /usr/share/atom/resources/app.asar/src/package.js:188:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:451:30)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -3:25.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:24.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "hide-files"
    ],
    "ignoredNames": [
      "*.pyc"
    ],
    "projectHome": "/home/joan/Projects"
  }
}
```

### Installed Packages

```coffee
# User
atom-sync, v0.4.4
color-picker, v2.0.4
django-templates, v0.5.0

# Dev
No dev packages
```

**Comment by dingjie** [comment]
I'm looking into it.

**Comment by dingjie** [comment]
Hi joannadal, try upgrading to the latest v0.4.5, it's now working on ubtuntu as well.

**Comment by joannadal** [comment]
Yes, it's fixed!
