### ISSUE TITLE
Uncaught Error: Cannot find module '../service/undefined'

### ISSUE THREAD

**Issue by bearTeddy** [dingjie/atom-sync#41]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-sync](https://github.com/dingjie/atom-sync) package, v0.7.3

### Stack Trace

Uncaught Error: Cannot find module '../service/undefined'

```
At module.js:340

Error: Cannot find module '../service/undefined'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.ServiceController.sync (/Users/bearteddy/.atom/packages/atom-sync/lib/controller/service-controller.coffee:93:10)
    at Object.module.exports.ServiceController.onSync (/Users/bearteddy/.atom/packages/atom-sync/lib/controller/service-controller.coffee:66:22)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-sync:download-directory (/Users/bearteddy/.atom/packages/atom-sync/lib/atom-sync.coffee:27:25)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
     -0:01.2.0 atom-sync:download-directory (div.header.list-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "Tern",
      "remote-edit",
      "git-status-utils",
      "npm",
      "close-tags",
      "git-control",
      "node-debugger",
      "ex-mode",
      "jshint",
      "activate-power-mode",
      "minimap",
      "open-on-github",
      "file-type-icons",
      "highlight-selected",
      "pane-by-type",
      "swackets"
    ],
    "packagesWithKeymapsDisabled": []
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-backbone, v0.6.1
atom-html-preview, v0.1.19
atom-jshint, v2.0.0
atom-sync, v0.7.3
atom-ternjs, v0.14.1
autoclose-html, v0.23.0
autocomplete-clang, v0.9.3
autocomplete-json, v5.0.2
autocomplete-modules, v1.5.1
background-tips, v0.26.0
build, v0.64.0
build-npm-apm, v0.12.0
busy, v0.5.0
clipboard-plus, v0.5.1
cursor-history, v0.5.9
file-types, v0.5.1
grammar-token-limit, v0.1.1
javascript-snippets, v1.2.1
language-ejs, v0.2.0
language-qml, v1.0.0
language-qtpro, v0.6.0
linter, v1.11.4
linter-clang, v3.4.4
merge-conflicts, v1.4.3
open-recent, v5.0.0
pigments, v0.29.0
project-manager, v2.9.7
symbols-tree-view, v0.13.1
sync-settings, v0.7.2
tabular, v0.1.0
terminal-plus, v0.14.5
underscorejs-snippets, v0.2.2
vim-mode, v0.65.1
vim-mode-clipboard-plus, v0.2.0
vim-mode-visual-block, v0.2.15
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by duncup** [comment]
I get this error too.

**Comment by Doubledream** [comment]
I get this error too.

**Comment by firasalkafri** [comment]
Any updates on this issue?

**Comment by firasalkafri** [comment]
The issue can be reproduced when enabling the "alwaysSyncAll" flag and could be avoided by disabling it

**Comment by psy0rz** [comment]
This issue still exists in 0.7.3.

It seems to get triggered by opening an existing file after starting atom.
