### ISSUE TITLE
Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by hultberg** [dingjie/atom-sync#46]
Atom 1.8.0

Using the keybinding I added in atom-sync to sync the whole project.

````
ReferenceError: _ is not defined
    at Object.module.exports.AtomSync.getProjectPath (/Users/edvin/github/atom-sync/lib/atom-sync.coffee:61:5)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-sync:upload-project (/Users/edvin/github/atom-sync/lib/atom-sync.coffee:23:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
````

**Comment by artempartos** [comment]
Got the same

**Comment by elliotaplant** [comment]
Looks like a pretty easy fix - lodash isn't imported in the `atom-sync.coffee` file. We just need to add this to the top of the file:
```coffee
_ = require 'lodash'
```
I'll make a PR for this if you want @dingjie
