### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mkoser** [dingjie/atom-sync#58]
[Enter steps to reproduce:]

1. Download `atom-sync` package
2. Right-click folder to sync, choose any option.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Fedora 25
**Thrown From**: [atom-sync](https://github.com/dingjie/atom-sync) package 0.7.3

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/mkoser/.atom/packages/atom-sync/lib/helper/config-helper.coffee:27

TypeError: Cannot read property 'length' of undefined
    at Object.isExcluded (/packages/atom-sync/lib/helper/config-helper.coffee:27:9)
    at Object.onSync (/packages/atom-sync/lib/controller/service-controller.coffee:49:27)
    at /packages/atom-sync/lib/atom-sync.coffee:27:25)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1168:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:19.9.0 tree-view:remove-project-folder (div.header.list-item.project-root-header)
     -3:18.3.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:08.5.0 atom-sync:configure (span.name.icon.icon-repo)
     -3:05.9.0 core:save (input.hidden-input)
     -2:53.2.0 atom-sync:upload-directory (span.name.icon.icon-repo)
  2x -0:14.5.0 atom-sync:download-directory (span.name.icon.icon-repo)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-sync 0.7.3 
atom-uikit 1.2.2 
autocomplete-python 1.8.60 
emmet 2.4.3 
file-icons 1.7.25 
git-plus 7.0.7 
language-ansible 0.2.1 
language-cfml 0.17.0 
language-powershell 4.0.0 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap 4.25.7 
multi-cursor 2.1.5 
pretty-json 1.6.1 
project-manager 3.3.3 
python-debugger 0.2.0 
remote-edit 1.9.0 
script 3.14.1 
```

**Comment by ayurmedia** [comment]
it seems you are missing the section option/exclude in your config file. 

```
exclude: [
    ".sync-config.cson"
    ".git"
    "node_modules"
    "tmp"
    "vendor"
  ]
```

or the filename passed to  "str" is not correct. 

```
isExcluded: (str, exclude) ->
    for pattern in exclude
      return true if (str.indexOf pattern) isnt -1
    return false
```

there is no error if `exclude: []` is an empty array. 
but you should not remove the excludes, so that config is not uploaded to server.
