### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by dingjie** [dingjie/atom-sync#6]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-sync](https://github.com/dingjie/atom-sync) package, v0.4.5

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:762

TypeError: Cannot read property 'indexOf' of undefined
  at Object.module.exports.ConfigHelper.isExcluded (/Users/dingjie/github/atom-sync/lib/helper/config-helper.coffee:33:20)
  at Object.module.exports.ServiceController.onSync (/Users/dingjie/github/atom-sync/lib/controller/service-controller.coffee:44:20)
  at Object.module.exports.ServiceController.onSave (/Users/dingjie/github/atom-sync/lib/controller/service-controller.coffee:27:10)
  at /Users/dingjie/github/atom-sync/lib/atom-sync.coffee:31:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:996:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:317:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
  2x -0:45.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:28.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:26.9.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:14.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.9.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:05.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "tomorrow-night-eighties-syntax"
    ],
    "disabledPackages": []
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
atom-sync, v0.4.5
autocomplete-php, v0.3.6
browser-plus, v0.0.23
coffee-compile, v0.16.1
color-picker, v2.0.7
css-snippets, v0.8.0
docs-snippets, v0.8.0
emmet, v2.3.10
file-icons, v1.5.7
fonts, v0.4.2
isotope-ui, v2.4.1
linter, v0.12.7
linter-csslint, v0.0.13
linter-htmlhint, v0.0.16
linter-jshint, v0.1.6
linter-less, v0.5.0
linter-php, v0.0.15
minimap, v4.10.0
minimap-find-and-replace, v4.2.0
pigments, v0.8.0
project-manager, v1.15.10
tomorrow-night-eighties-syntax, v0.6.1

# Dev
No dev packages
```

**Comment by pankovpv** [comment]
It always happens then I am saving file with tree view panel hidden [Cmd + \]. With tree panel open sync works.

**Comment by Goddard** [comment]
Always happens on Ubuntu 15.04 when tree view is close.

**Comment by Goddard** [comment]
Also happens when you create a new file with ctrl + n and then ctrl + s

**Comment by mrthebob** [comment]
+1 Same here.

**Comment by CodeMySky** [comment]
It happens when I created a file and renamed it, and try to save it. 
On Mac OSX 10, and Atom 1.0.3

**Comment by exanter** [comment]
mac os 10.10.4, atom 1.0.5 for me, happened when saving a file, with left tree view open.

**Comment by mrthebob** [comment]
Happens for me when the tree view is closed.

**Comment by jpvelez** [comment]
Happens for me with tree view open, when I try to save a new file while synching with the server.

**Comment by chris-aeviator** [comment]
happens to me with both, tree open and closed, osx
