### ISSUE TITLE
Failed to activate the atom-sync package

### ISSUE THREAD

**Issue by trawler** [dingjie/atom-sync#65]
[Enter steps to reproduce:]

1. pulled the latest version of this plugin into ~/.apm/packages
2. upgraded atom to latest version (1.17.2)

I can now see the sync submenu when right clicking, but the menu items don't work.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-sync](https://github.com/dingjie/atom-sync) package 0.7.3

### Stack Trace

Failed to activate the atom-sync package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:1)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at /packages/atom-sync/lib/atom-sync.coffee:3:7)
    at /packages/atom-sync/lib/atom-sync.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:73:1)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:1)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:242:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:642:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:623:1
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:1)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:600:1)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:832:1
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-jinja2 0.6.0 
atom-sync 0.7.3 
autocomplete-ruby 0.2.8 
busy-signal 1.4.1 
git-plus 7.9.2 
git-plus-plus 1.1.0 
git-plus-toolbar 1.0.1 
intentions 1.1.2 
keybinding-cheatsheet 0.1.1 
language-puppet 0.22.0 
language-r 0.4.1 
language-terraform 0.8.1 
linter 2.1.4 
linter-puppet-lint 0.8.2 
linter-ruby 1.2.5 
linter-ui-default 1.6.0 
remote-atom 1.3.10 
ruby-block 0.3.6 
tool-bar 1.1.0 
vim-mode-plus 0.93.0 
```

**Comment by trawler** [comment]
found the issue was related to a missing node_modules directory inside the module directory
